global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'semki_dev'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'semki_prod'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['semki-server:8080']

  - job_name: mongodb
    scrape_interval: 5s
    static_configs:
      - targets: ['mongodb_exporter:9216']
